[package]
name = "asset_store"
version = "0.0.2"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.hyper]
version = "0.5.2"
optional = true

[dependencies]
resources_package = "0.0.8"
resources_package_package = "0.0.6"

[features]
default = ["url"]
url = ["hyper"]

